sudo: false
language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '11'
  - '12'
script:
  - yarn run build
#after_success:
#  - npx codecov
branches:
  only:
    - master
